# Generated by Django 6.1.1 on 2026-09-21 09:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('recorded_at', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='inventory.part')),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
    ]
