# Generated by Django 6.1.1 on 2026-09-21 10:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_pricerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('ordered_on', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ordered', 'Order Placed'), ('received', 'Received'), ('cancelled', 'Cancelled')], max_length=20)),
                ('note', models.CharField(blank=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inventory.part')),
            ],
        ),
    ]
