# Generated by Django 6.1.1 on 2026-09-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='parts/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Order Placed'), ('received', 'Received'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], max_length=20),
        ),
    ]
